name: crossbow
author: Stijn Van Bael <stijn.van.bael@appify.be>
homepage: https://github.com/stijnvanbael/box
version: 0.0.2
description: Crossbow framework
dependencies:
  io: ">=0.1.0-git <0.2.0-git"
  exportable: ">=0.1.0 <0.2.0"
  reflective: ">=0.0.0 <0.1.0"
  box: ">=0.0.0 <0.1.0"
dev_dependencies:
  unittest: any
